disabled_rules: # rule identifiers to exclude from running
- type_name
- identifier_name
- opening_brace
- line_length
- type_body_length
- function_body_length
- file_length
- cyclomatic_complexity
- weak_delegate
- nesting
#- discarded_notification_center_observer
- statement_position
- trailing_whitespace
- function_parameter_count
- todo
- switch_case_alignment
opt_in_rules:
- array_init
- attributes
- closure_spacing
##  - conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
# - empty_count
##  - explicit_acl
##  - explicit_enum_raw_value
- explicit_init
##  - explicit_top_level_acl
##  - explicit_type_interface
##  - extension_access_modifier
##  - file_header
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicit_return
# - implicitly_unwrapped_optional
- joined_default_parameter
## - let_var_whitespace
## - literal_expression_end_indentation
## - modifier_order
## - multiline_arguments
- multiline_function_chains
- multiline_parameters
- nimble_operator
##  - no_extension_access_modifier
##  - no_grouping_extension
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
# - prefixed_toplevel_constant
- private_action
# - private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
#  - sorted_imports
##  - strict_fileprivate
- switch_case_on_newline
#- trailing_closure
- unavailable_function
# - unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition
force_cast: warning # implicitly

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
